title: "Abdoulaye SANOGO"
logo: img/profil.jpg
description: "Portfolio Reseau securite & cloud"
remote_theme: pages-themes/hacker@v0.2.0
plugins:

- jekyll-remote-theme # add this line to the plugins list if you already have one
lang: fr
